// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKWkr2bTqgCI9DMtyao35ZTUVjsp6YUzY',
    appId: '1:957908341090:web:f9eef80798b41bf4addc3b',
    messagingSenderId: '957908341090',
    projectId: 'arya-heck-auth',
    authDomain: 'arya-heck-auth.firebaseapp.com',
    storageBucket: 'arya-heck-auth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBrCW9mOOUhxHm3Y4Jjv9-CN6ZThpybrk',
    appId: '1:957908341090:android:e9160e67a5a87e73addc3b',
    messagingSenderId: '957908341090',
    projectId: 'arya-heck-auth',
    storageBucket: 'arya-heck-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRYK7zn1oR35DWx48ZMf6DuahslKg5roU',
    appId: '1:957908341090:ios:6acecf91a0088172addc3b',
    messagingSenderId: '957908341090',
    projectId: 'arya-heck-auth',
    storageBucket: 'arya-heck-auth.firebasestorage.app',
    iosBundleId: 'com.example.aryaHeck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRYK7zn1oR35DWx48ZMf6DuahslKg5roU',
    appId: '1:957908341090:ios:6acecf91a0088172addc3b',
    messagingSenderId: '957908341090',
    projectId: 'arya-heck-auth',
    storageBucket: 'arya-heck-auth.firebasestorage.app',
    iosBundleId: 'com.example.aryaHeck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKWkr2bTqgCI9DMtyao35ZTUVjsp6YUzY',
    appId: '1:957908341090:web:e823f5045581109daddc3b',
    messagingSenderId: '957908341090',
    projectId: 'arya-heck-auth',
    authDomain: 'arya-heck-auth.firebaseapp.com',
    storageBucket: 'arya-heck-auth.firebasestorage.app',
  );
}
